BusinessManagementSystemApp/Controllers/SalesController.cs
using AutoMapper;
using BusinessManagementSystemApp.BLL.BLL;
using BusinessManagementSystemApp.BLL.Manager;
using BusinessManagementSystemApp.Models;
using BusinessManagementSystemApp.Models.Models;
using Rotativa;
using System;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BusinessManagementSystemApp.Controllers
{
    public class SalesController : Controller
    {
        SalesManager _salesManager = new SalesManager();
        private SalesDetails _salesDetails = new SalesDetails();
        private Sale sale = new Sale();
        CustomerManager _customerManager = new CustomerManager();
        ProductManager _productManager = new ProductManager();
        // GET: Sales
        [HttpGet]
        public ActionResult Save()
        {
            SalesSaveViewModel salesModelVm = new SalesSaveViewModel();
            salesModelVm.CustomerList = _customerManager.FindAll().Select(c => new SelectListItem()
            {
                Value = c.Id.ToString(),
                Text = c.CustName
            });
            return View(salesModelVm);
        }
        [HttpPost]
        public ActionResult Save(SalesSaveViewModel salesModelVm)
        {
            if (ModelState.IsValid)
            {
                SalesDetails salesModel = new SalesDetails();
                salesModel = Mapper.Map<SalesDetails>(salesModelVm);
                if (_salesManager.Save(salesModel))
                {
                    ViewBag.SuccessMsg = "Data Saved SuccessFully!";
                }
                else
                {
                    ViewBag.FailMsg = "Data Saved Fail!";
                }
            }
            else
            {
                ViewBag.FailMsg = "Data Validtion Fail!";
            }
            salesModelVm.CustomerList = _customerManager.FindAll().Select(c => new SelectListItem()
            {
                Value = c.Id.ToString(),
                Text = c.CustName
            });
            return View(salesModelVm);
        }
        public ActionResult Delete(Sale sale)
        {
            sale.Id = sale.Id;

            if (_salesManager.Delete(sale))
            {
                ViewBag.SuccessMsg = "Data Delete SuccessFully!";
                TempData["SuccessMessage"] = "Data Delete SuccessFully!";
                return RedirectToAction("FindAll");
            }
            else
            {
                ViewBag.FailMsg = "Data Delete Fail!";
                TempData["SuccessMessage"] = "Data Delete Fail!";
                return RedirectToAction("FindAll");
            }

            return View();
        }
        [HttpGet]
        public ActionResult FindAll(SalesSaveViewModel salesSaveViewModel)
        {
            SalesSaveViewModel salesSaveVM = new SalesSaveViewModel();

            salesSaveVM.SalesList = _salesManager.FindAll();

            salesSaveVM.CustomerList = _customerManager.FindAll()
                .Select(c => new SelectListItem()
                {
                    Value = c.Id.ToString(),
                    Text = c.CustName
                });
            return View(salesSaveVM);
        }
        [HttpPost]
        public ActionResult FindAll(CustomerModel customerModel)
        {
            SalesSaveViewModel salesSaveVM = new SalesSaveViewModel();
            var customers = _customerManager.FindAll();
            if (customerModel.CustName != null)
            {
                customers = customers.Where(c => c.CustName.ToLower().Contains(customerModel.CustName.ToLower())).ToList();
            }

            foreach (var v in customers)
            {
                customerModel.Id = v.Id;
            }
            var salesList = _salesManager.FindAll();
            if (customerModel.Id != null)
            {
                salesList = salesList.Where(c => c.CustomerModelsId == customerModel.Id).ToList();
            }

            salesSaveVM.SalesList = salesList;

            salesSaveVM.CustomerList = _customerManager.FindAll()
                .Select(c => new SelectListItem()
                {
                    Value = c.Id.ToString(),
                    Text = c.CustName
                });
            return View(salesSaveVM);
        }

        public ActionResult BatchSalesAdd()
        {
            var customers = _customerManager.FindAll();
            ViewBag.Customers = new SelectList(customers, "Id", "CustName");

            var products = _productManager.GetProducts();
            ViewBag.Products = new SelectList(products, "ProductId", "ProductName");

            return View();
        }

        [HttpPost]
        public ActionResult BatchSalesAdd(SalesSaveViewModel Model)
        {
            try
            {
                sale.CustomerModelsId = Model.CustomerModelsId;
                int loyaltyPoint = (Convert.ToInt32(Model.CustomerPayment) / 1000);
                CustomerModel customer = new CustomerModel();
                customer.Id = sale.CustomerModelsId;
                var aCustomer = _customerManager.FindById(customer);
                if (Model.Discount > 0)
                {
                    aCustomer.CustLoyaltyPoints = aCustomer.CustLoyaltyPoints - (Convert.ToInt32(Model.Discount * 10));
                }
                else
                {
                    aCustomer.CustLoyaltyPoints = aCustomer.CustLoyaltyPoints + loyaltyPoint;
                }


                sale.Date = Model.Date;
                sale.Comments = Model.Comments;
                sale.CustomerPayment = Model.CustomerPayment;
                sale.DiscountAmt = Model.DiscountAmt;
                sale.Discount = Model.Discount;
                sale.SalesDetailsList = Model.SalesDetailsList;
                if (_salesManager.SaveSalesProduct(sale))
                {
                    if (_customerManager.Update(aCustomer))
                    {
                        var customersList = _customerManager.FindAll();
                        ViewBag.Customers = new SelectList(customersList, "Id", "CustName");

                        var products = _productManager.GetProducts();
                        ViewBag.Products = new SelectList(products, "ProductId", "ProductName");
                        ViewBag.SuccessMsg = "Data Saved SuccessFully!";
                        return View();
                    }

                }
                else
                {
                    ViewBag.FailMsg = "Data Saved Fail!";
                }

            }
            catch(Exception EX)
            {
                ViewBag.FailMsg = "Something went wrong";
            }
         

            return View(Model);
        }

        public JsonResult GetCustLoyaltyPoints(int CustId)
        {
            var customer = _salesManager.GetCustLoyaltyPoints(CustId);

            return Json(customer, JsonRequestBehavior.AllowGet);
        }
        public JsonResult ProductDetails(int productId)
        {
            ProductViewModel model = new ProductViewModel();
            Product product = new Product();
            product.ProductId = productId;
            var aProduct = _productManager.GetProductById(product);
            string productCode = aProduct.ProductCode;
            model = _salesManager.ProductDetails(product);
            model.ProductCode = productCode;

            return Json(model, JsonRequestBehavior.AllowGet);
        }


       
        [HttpGet]
        public ActionResult VoucherDetails(SalesSaveViewModel salesSaveViewModel)
        {
            SalesSaveViewModel salesSaveVM = new SalesSaveViewModel();

            salesSaveVM.SalesList = _salesManager.FindAll();

            salesSaveVM.CustomerList = _customerManager.FindAll()
                .Select(c => new SelectListItem()
                {
                    Value = c.Id.ToString(),
                    Text = c.CustName
                });
            return View(salesSaveVM);
        }
        [HttpPost]
        public ActionResult VoucherDetails(SalesDetails salesDetails)
        {
            SalesSaveViewModel salesSaveVM = new SalesSaveViewModel();
            var customers = _customerManager.FindAll();

            foreach (var v in customers)
            {
                salesDetails.Id = v.Id;
            }
            var salesDetailsList = _salesManager.FindAll();

            salesSaveVM.CustomerList = _customerManager.FindAll()
                .Select(c => new SelectListItem()
                {
                    Value = c.Id.ToString(),
                    Text = c.CustName
                });
            return View(salesSaveVM);
        }

        public ActionResult ExportPDF()
        {
            return new ActionAsPdf("FindAll")
            {
                FileName = Server.MapPath("~/Content/ListSales.pdf")
            };
        }



    }
}

BusinessManagementSystemApp/Controllers/StockController.cs
using BusinessManagementSystemApp.BLL.BLL;
using BusinessManagementSystemApp.BLL.Manager;
using BusinessManagementSystemApp.Models;
using BusinessManagementSystemApp.Models.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BusinessManagementSystemApp.Controllers
{
    public class StockController : Controller
    {
        StockManager _stockManager = new StockManager();
        ProductManager _productManager = new ProductManager();
        CategoryManager _categoryManager = new CategoryManager();
        Product _product = new Product();


        // GET: Stock
        public ActionResult Search()
        {

            return View();
        }



        [HttpPost]
        public ActionResult Search(StockVM  stockVM, DateTime startDate, DateTime endDate)
        {
      

            _product.ProductName = stockVM.ProductName;
            _product.CategoryName = stockVM.CategoryName;
            try
            {
                List<StockVM> products = _productManager.GetProductsWithCatagory(_product).Select(c => new StockVM
                {
                    ProductId = c.ProductId,
                    ProductName = c.ProductName,
                    CategoryName = c.Category.CategoryName,
                    ReorderLevel = c.ReorderLevel,
                    Code = c.ProductCode,
                }).ToList();

                foreach (var product in products)
                {

                    Product pro = new Product();
                    pro.ProductId = product.ProductId;
                    pro.ProductName = product.ProductName;
                    var aProduct = _stockManager.GetProductAvailableQuantity(pro);
                    var expireDate = _productManager.PurchaseDetails(pro, startDate, endDate);
                    foreach (var item in products)
                    {

                        if (item.ProductName == pro.ProductName)
                        {
                            item.Quantity = aProduct;
                            item.ProductId = pro.ProductId;
                            item.ExpireDate = expireDate.ExpireDate;

                            TempData["SuccessMessage"] = "Search Successfully";
                        }


                    }

                }
                ViewBag.Products = products;
            }
            catch (Exception ex)
            {
                TempData["SuccessMessage"] = "Search data not found";
            }


            return View();
        }
      
    }
}

BusinessManagementSystemApp/Controllers/SupplierController.cs
using AutoMapper;
using BusinessManagementSystemApp.BLL.BLL;
using BusinessManagementSystemApp.BLL.Manager;
using BusinessManagementSystemApp.Models;
using BusinessManagementSystemApp.Models.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace BusinessManagementSystemApp.Controllers
{
    public class SupplierController : Controller
    {
        SupplierManager _supplierManager = new SupplierManager();
        SupplierVM _supplierVM = new SupplierVM();
        private Supplier _supplier = new Supplier();
        string _fileName = string.Empty;
        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }

        // GET: Suppliers
        [HttpPost]
        public ActionResult Add(SupplierVM supplierVM, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                _fileName = Path.GetFileNameWithoutExtension(image.FileName);
                string extension = Path.GetExtension(image.FileName);
                _fileName = _fileName + DateTime.Now.ToString("yymmssfff") + extension;
                supplierVM.Image = "~/images/SupplierImage/" + _fileName;
                var supplier = Mapper.Map<Supplier>(supplierVM);
                if (_supplierManager.Add(supplier))
                {
                    _fileName = Path.Combine(Server.MapPath("~/images/SupplierImage/"), _fileName);
                    image.SaveAs(_fileName);
                    ViewBag.SuccessMsg = "Saved";
                    TempData["SuccessMessage"] = "Saved Successfully";
                    return RedirectToAction("Show");
                }
                else
                {
                    ViewBag.FailMsg = "Save Failed!!";
                }
            }
            else
            {
                ViewBag.FailMsg = "An error occurred, please try again later!";
            }

            return View(supplierVM);
        }

        [HttpGet]
        public ActionResult Delete(int Id)
        {
            _supplier.Id = Id;
            var supplier = _supplierManager.GetByID(_supplier);
            _supplierVM = Mapper.Map<SupplierVM>(supplier);
            return View(_supplierVM);
        }
        [HttpPost]
        public ActionResult Delete(SupplierVM supplierVM)
        {

            if (ModelState.IsValid)
            {
                var supplier = Mapper.Map<Supplier>(supplierVM);
                if (_supplierManager.Delete(supplier))
                {
                    TempData["SuccessDeleteMessage"] = "Record Delete Successfully";
                    return RedirectToAction("Show");
                }
                else
                {
                    ViewBag.FailMsg = "Failed";
                }

            }
            else
            {
                ViewBag.FailMsg = "Validation Error";
            }

            return View(supplierVM);
        }
        [HttpGet]
        public ActionResult Edit(int Id)
        {
            _supplier.Id = Id;
            var supplier = _supplierManager.GetByID(_supplier);
            _supplierVM = Mapper.Map<SupplierVM>(supplier);
            return View(_supplierVM);
        }
        [HttpPost]
        public ActionResult Edit(SupplierVM supplierVM, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                var supplier = Mapper.Map<Supplier>(supplierVM);
                _fileName = Path.GetFileNameWithoutExtension(image.FileName);
                string extension = Path.GetExtension(image.FileName);
                _fileName = _fileName + DateTime.Now.ToString("yymmssfff") + extension;
                supplierVM.Image = "~/images/SupplierImage/" + _fileName;
                _fileName = Path.Combine(Server.MapPath("~/images/SupplierImage/"), _fileName);
                image.SaveAs(_fileName);
                if (_supplierManager.Update(supplier))
                {

                    ViewBag.SuccessMsg = "Updated";
                    TempData["SuccessUpdateMessage"] = "Record Updated SuccessFully!";
                    return RedirectToAction("Show");


                }
                else
                {
                    ViewBag.FailMsg = "Failed";
                }
            }
            else
            {
                ViewBag.FailMsg = "Validation Error";
            }

            return View(supplierVM);
        }
        [HttpGet]
        public ActionResult Details(int Id)
        {
             _supplier.Id = Id;
            var supplier = _supplierManager.GetByID(_supplier);
            _supplierVM = Mapper.Map<SupplierVM>(supplier);
            return View(_supplierVM);
        }
        [HttpPost]
        public ActionResult Details(SupplierVM supplierVM, HttpPostedFileBase image)
        {
            Supplier supplier = new Supplier();
            supplier = Mapper.Map<Supplier>(supplierVM);
            var suppliers = _supplierManager.GetAll();

            return View(supplierVM);
        }
        [HttpGet]
        public ActionResult Show()
        {
            _supplierVM.Suppliers = _supplierManager.GetAll();
            return View(_supplierVM);
        }
        [HttpPost]
        public ActionResult Show(SupplierVM supplierVM )
        {
            Supplier supplier = new Supplier();
            supplier = Mapper.Map<Supplier>(supplierVM);
            var suppliers = _supplierManager.GetAll();

            if (supplierVM.Name != null)
            {

                suppliers = suppliers.Where(c => c.Name.ToLower().Contains(supplierVM.Name.ToLower())).ToList();
            }

            supplierVM.Suppliers = suppliers;
            return View(supplierVM);
        }
        public JsonResult IsExistSupplierName(string supplierCode)
        {
            bool isExist = false;
            Supplier supplier = new Supplier();
            supplier.Code = supplierCode;
            isExist = _supplierManager.IsExistSupplier(supplier);
            return Json(isExist, JsonRequestBehavior.AllowGet);
        }
    }
}

BusinessManagementSystemApp/Views/Shared/Dashboard.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>.::Admin-Panel::.</title>
    <!-- Bootstrap -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <!-- Font Awesome -->
    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-reboot.min.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.css" rel="stylesheet" />
    <script src="~/Content/vendors/nprogress/nprogress.js"></script>
    <link href="~/Content/green.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-progressbar-3.3.4.css" rel="stylesheet" />
    <link href="~/Content/jqvmap.min.css" rel="stylesheet" />
    <link href="~/Content/daterangepicker.css" rel="stylesheet" />
    <link href="~/Content/custom.min.css" rel="stylesheet" />
    <link href="~/Content/custom.css" rel="stylesheet" />
    <link href="~/Styles/sweetalert.css" rel="stylesheet" />
    <script src="~/Styles/SweetAlert.js"></script>
    <link href="~/Content/sweetalert.min.css.map" />
</head>

<body class="nav-md">
    <div class="container body">
        <div class="main_container">
            <div class="col-md-3 left_col">
                <div class="left_col scroll-view">
                    <div class="navbar nav_title" style="border: 0;">
                        <a href="@Url.Action("Index","Home")" class="site_title"><i class="fa fa-paw"></i> <span>Small Business Management System!</span></a>
                    </div>

                    <div class="clearfix"></div>

                    <!-- menu profile quick info -->
                    <div class="profile clearfix">
                        <div class="profile_pic">

                            <img alt="..." class="img-circle profile_img" src="~/images/img.jpg" />
                        </div>
                        <div class="profile_info">
                            <span>Welcome,</span>
                            <h2>Ibrahim Hasan</h2>
                         
                        </div>
                    </div>
                    <!-- /menu profile quick info -->

                    <br />

                    <!-- sidebar menu -->
                    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                        <div class="menu_section">
                            <ul class="nav side-menu">




                                <li>
                                    <a><i class="fa fa-desktop"></i>Category<span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu">
                                        <li><a href="@Url.Action("SaveCategory","Category")">Category Setup</a></li>
                                        <li><a href="@Url.Action("Index","Category")">Category List</a></li>
                                    </ul>
                                </li>
                                <li>
                                    <a><i class="fa fa-desktop"></i>Product<span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu">
                                        <li><a href="@Url.Action("SaveProduct","Product")">Product Setup</a></li>
                                        <li><a href="@Url.Action("Index","Product")">Product List</a></li>
                                    </ul>
                                </li>
                                <li>
                                    <a><i class="fa fa-desktop"></i> Party Module<span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu">
                                        <li><a href="@Url.Action("Insert","CustomerInfo")">Customer Setup </a></li>
                                        <li><a href="@Url.Action("FindAll","CustomerInfo")">Customer List </a></li>
                                        <li><a href="@Url.Action("Add","Supplier")">Supplier Setup</a></li>
                                        <li><a href="@Url.Action("Show","Supplier")">Supplier List</a></li>
                                    </ul>
                                </li>
                                <li>
                                    <a><i class="fa fa-desktop"></i>Purchase Module<span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu">
                                        <li><a href="@Url.Action("InsertPurchaseProduct","Purchase")">  Purchase Entry </a></li>
                                        <li><a href="@Url.Action("Index","Purchase")">Purchase List </a></li>
                                        @*<li><a href="#">Purchase Confirm</a></li>
                                            <li><a href="#">Purchase Search </a></li>*@
                                    </ul>
                                </li>
                                <li>
                                    <a><i class="fa fa-desktop"></i>Sales Module <span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu">
                                        <li><a href="@Url.Action("BatchSalesAdd","Sales")"> Sales Entry </a></li>
                                        <li><a href="@Url.Action("FindAll","Sales")">Sales List</a></li>
                                        @*<li><a href="#">Sales Confirm</a></li>
                                            <li><a href="#">Sales Search </a></li>*@
                                    </ul>
                                </li>
                                <li>
                                    <a><i class="fa fa-desktop"></i> Stock Module <span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu">
                                        <li><a href="@Url.Action("Search","Stock")">Periodical Stock Report</a></li>
                                    </ul>
                                </li>
                                <li>
                                    <a><i class="fa fa-desktop"></i>Reporting Module <span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu">
                                        <li><a href="@Url.Action("PeriodictIncomeReport","Reporting")">Periodic Income Expense Report on Sales </a></li>
                                        <li><a href="@Url.Action("PeriodicIncomeExpenseOnPurchase","Reporting")">Periodic Income Expense Report on Purchase </a></li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <!-- /sidebar menu -->
                    <!-- /menu footer buttons -->
                    <div class="sidebar-footer hidden-small">
                      
                        <a data-toggle="tooltip" data-placement="top" title="Logout" href="/Login/Index">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
                        </a>
                    </div>
                    <!-- /menu footer buttons -->
                </div>
            </div>

            <!-- top navigation -->
            <div class="top_nav">
                <div class="nav_menu">
                    <nav>
                        <div class="nav toggle">
                            <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                        </div>
                        @if (ViewBag.SuccessMsg != null)
                        {
                            <div id="alert"><i class="fa fa-check-square-o"></i> @ViewBag.SuccessMsg</div>
                        }
                        @if (ViewBag.FailMsg != null)
                        {
                            <div id="danger"> <i class="fa fa-close"></i>@ViewBag.FailMsg</div>
                        }
                            <ul class="nav navbar-nav navbar-right">
                             
                                
                              
                               

                                <li role="presentation" class="dropdown">
                                   
                                </li>
                            </ul>
                    </nav>
                </div>
            </div>
            <!-- /top navigation -->
            <!-- page content -->
            <div class="right_col" role="main">
                <div class="">
                    <div class="row">
                        @RenderBody()
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
            <!-- /page content -->
            <!-- footer content -->
            <footer>
                <div class="pull-right">
                    Developed & Maintained By- <a href="#">Ibrahim</a>
                </div>
                <div class="clearfix"></div>
            </footer>
            <!-- /footer content -->
        </div>
    </div>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/SweetAlert.js"></script>
    <!-- jQuery -->
    <a href="~/Scripts/sweetalert.json">~/Scripts/sweetalert.json</a>
    <script src="~/Scripts/validator.js"></script>
    @*<script src="~/Scripts/jquery-3.0.0.min.js"></script>*@
    <script src="~/Scripts/jquery.min.js"></script>
    <script src="~/Scripts/validator.js"></script>
    <script src="~/Scripts/sweetalert.min.js"></script>
    <!-- Bootstrap -->
    <script src="~/Scripts/bootstrap.min.js"></script>
    <!-- FastClick -->
    <script src="~/Scripts/fastclick.js"></script>
    <!-- NProgress -->
    <script src="~/Scripts/nprogress.js"></script>
    <!-- validator -->
    @*<script src="~/Scripts/validator.js"></script>*@
    <!-- Custom Theme Scripts -->
    <script src="~/Scripts/custom.min.js"></script>
    <script src="~/Scripts/SweetAlert.js"></script>
    <script src="~/Scripts/sweetalert.min.js"></script>
    <link href="~/Styles/sweetalert.css" rel="stylesheet" />
    @RenderSection("Scripts", false)
</body>
</html>